formatting and parsing messages
vladaviedov/air pull request #10
Opened 2024-03-18 01:28 UTC by caiodasilva2005

2024-03-18 01:36 UTC, vladaviedov requested changes
The body of the message does not have a fixed length.

2024-03-18 01:36 UTC, vladaviedov commented on .vscode/settings.json
gitignore this folder

2024-03-18 01:36 UTC, vladaviedov commented on shared/include/messages.hpp
> +{
Put bracket on the same line

2024-03-18 01:36 UTC, vladaviedov commented on shared/include/messages.hpp
> +#ifndef MESSAGES_HPP
use #pragma once

2024-03-18 01:36 UTC, vladaviedov commented on shared/include/messages.hpp
> +msg_t parse_message(std::string str_msg);
Pass by reference

2024-03-18 01:36 UTC, vladaviedov commented on shared/src/messages.cpp
> +        .receiver_id = str_msg.substr(20,21),
Message body is dynamically sized, you can't do this

2024-03-18 01:36 UTC, vladaviedov commented on shared/include/messages.hpp
> +#endif
Files should end with an empty line

2024-03-19 01:40 UTC, vladaviedov commented on shared/src/messages.cpp
> +    std::string msg_header = "AIRv1.0";
mark as constexpr

2024-03-21 02:29 UTC, closed without merging

2024-03-21 02:29 UTC, caiodasilva2005 commented
made a new branch because I did something stupid in this one