i2c drivers
vladaviedov/air pull request #4
Opened 2024-03-16 15:20 UTC by Sabramz

These are probably ass. Also the includes aren't there cuz idk what i need to include. Just tell me and ill add em.

2024-03-16 15:56 UTC, vladaviedov requested changes
See my comments.
Please put newlines at the ends of files.
We need i2c-tools to use SMBus, I will add that today.

2024-03-16 15:56 UTC, vladaviedov commented on driver/include/i2c.hpp
> +
cstdint missing

2024-03-16 15:56 UTC, vladaviedov commented on driver/include/i2c.hpp
> +    i2c(const uint8_t dev_addr);
Argument and member name are the same

2024-03-16 15:56 UTC, vladaviedov commented on driver/include/i2c.hpp
> +     * @param[in] data - Data buffer to write to.
Data buffer is out, if you are reading

2024-03-16 15:56 UTC, vladaviedov commented on driver/include/i2c.hpp
> +    int write(uint8_t reg, char* data, uint8_t size);
size - make uint32_t
data - const
return val - make boolean

2024-03-16 15:56 UTC, vladaviedov commented on driver/src/i2c.cpp
> +    int fd;
remove, fd is a member

2024-03-16 15:56 UTC, vladaviedov commented on driver/src/i2c.cpp
> +    int adapter_nr = 1;
Make it a constexpr in device.hpp

2024-03-16 15:56 UTC, vladaviedov commented on driver/src/i2c.cpp
> +    snprintf(filename, 31, "/dev/i2c-%d", adapter_nr);
32, snprintf accounts for null char; std::snprintf in cpp

2024-03-16 15:56 UTC, vladaviedov commented on driver/src/i2c.cpp
> +    size += 1;
This will cause a segfault

2024-03-16 15:56 UTC, vladaviedov commented on driver/src/i2c.cpp
> +i2c::read(char* data, uint8_t size) {
Missing return type

2024-03-16 15:56 UTC, vladaviedov commented on driver/include/i2c.hpp
> +    int read(char* data, uint8_t size);
Return the size of the read buffer

read/write functions should be marked const

2024-03-16 15:56 UTC, vladaviedov commented on driver/src/i2c.cpp
> +    *buf[0] = reg;
Segfault

2024-03-16 15:56 UTC, vladaviedov commented on driver/src/i2c.cpp
> +        throw std::runtime_error("Failed to write i2c");
Return int result

2024-03-16 15:56 UTC, vladaviedov commented on .gitignore
> +Dockerfile
It's fine to commit the dockerfile if you have a working config

2024-03-16 15:56 UTC, vladaviedov commented on driver/include/i2c.hpp
> +
Missing destructor

2024-03-19 13:32 UTC, Sabramz commented on driver/include/i2c.hpp
> +    int write(uint8_t reg, char* data, uint8_t size);
Why boolean?

2024-03-19 13:36 UTC, vladaviedov commented on driver/include/i2c.hpp
> +    int write(uint8_t reg, char* data, uint8_t size);
It should show if write was successful or not, returning bytes written isn't very helpful above this layer

2024-03-19 13:38 UTC, Sabramz commented on driver/include/i2c.hpp
> +    int write(uint8_t reg, char* data, uint8_t size);
ok ez

2024-03-20 14:18 UTC, vladaviedov approved these changes

2024-03-20 14:19 UTC, merged